export const TV_SHOWS = [
  {
    Title: "How I Met Your Mother",
    Year: "2005–2014",
    Rated: "TV-14",
    Released: "19 Sep 2005",
    Runtime: "22 min",
    genre: "Comedy, Romance",
    Director: "N/A",
    Writer: "Carter Bays, Craig Thomas",
    Actors: "Josh Radnor, Jason Segel, Cobie Smulders",
    Plot:
      "A father recounts to his children - through a series of flashbacks - the journey he and his four best friends took leading up to him meeting their mother.",
    Language: "English, Persian, Chinese",
    Country: "United States",
    Awards: "Won 10 Primetime Emmys. 26 wins & 95 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/gvEisYtZ0iBMjnO3zqFU2oM26oM.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.3/10" }],
    Metascore: "N/A",
    imdbRating: "8.3",
    imdbVotes: "647,227",
    imdbID: "tt0460649",
    Type: "series",
    totalSeasons: "9",
    Response: "True",
  },
  {
    Title: "Euphoria",
    Year: "2019–",
    Rated: "TV-MA",
    Released: "16 Jun 2019",
    Runtime: "55 min",
    genre: "Drama",
    Director: "N/A",
    Writer: "Sam Levinson",
    Actors: "Hunter Schafer, Zendaya, Angus Cloud",
    Plot:
      "A look at life for a group of high school students as they grapple with issues of drugs, sex, and violence.",
    Language: "English",
    Country: "United States",
    Awards: "Won 3 Primetime Emmys. 15 wins & 47 nominations total",
    Poster: "https://images.fanart.tv/fanart/euphoria-2019-5ec8c62aa702d.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.4/10" }],
    Metascore: "N/A",
    imdbRating: "8.4",
    imdbVotes: "101,822",
    imdbID: "tt8772296",
    Type: "series",
    totalSeasons: "2",
    Response: "True",
  },
  {
    Title: "Peacemaker",
    Year: "1990",
    Rated: "R",
    Released: "08 Feb 1991",
    Runtime: "100 min",
    genre: "Action, Romance, Sci-Fi",
    Director: "Kevin Tenney",
    Writer: "Kevin Tenney",
    Actors: "Robert Forster, Lance Edwards, Hilary Shepard",
    Plot:
      "A doctor (Shepard) gets caught up in a war between two aliens (Edwards, Forster).",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://www.themoviedb.org/t/p/w500_and_h282_face/ctxm191q5o3axFzQsvNPlbKoSYv.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "5.3/10" }],
    Metascore: "N/A",
    imdbRating: "5.3",
    imdbVotes: "567",
    imdbID: "tt0100343",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Book of Boba Fett",
    Year: "2021–",
    Rated: "TV-14",
    Released: "29 Dec 2021",
    Runtime: "N/A",
    genre: "Action, Adventure, Sci-Fi",
    Director: "N/A",
    Writer: "Jon Favreau",
    Actors: "Temuera Morrison, Ming-Na Wen, Matt Berry",
    Plot:
      "Bounty hunter Boba Fett & mercenary Fennec Shand navigate the underworld when they return to Tatooine to claim Jabba the Hutt's old turf.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.0/10" }],
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "20,147",
    imdbID: "tt13668894",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "Peaky Blinders",
    Year: "2013–2022",
    Rated: "TV-MA",
    Released: "30 Sep 2014",
    Runtime: "60 min",
    genre: "Crime, Drama",
    Director: "N/A",
    Writer: "Steven Knight",
    Actors: "Cillian Murphy, Paul Anderson, Helen McCrory",
    Plot:
      "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
    Language: "English, Romanian, Irish Gaelic, Italian, Yiddish",
    Country: "United Kingdom",
    Awards: "Won 1 BAFTA Film Award21 wins & 47 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.8/10" }],
    Metascore: "N/A",
    imdbRating: "8.8",
    imdbVotes: "441,495",
    imdbID: "tt2442560",
    Type: "series",
    totalSeasons: "6",
    Response: "True",
  },
  {
    Title: "The Flash",
    Year: "2014–",
    Rated: "TV-PG",
    Released: "07 Oct 2014",
    Runtime: "43 min",
    genre: "Action, Adventure, Drama",
    Director: "N/A",
    Writer: "Greg Berlanti, Geoff Johns, Andrew Kreisberg",
    Actors: "Grant Gustin, Candice Patton, Danielle Panabaker",
    Plot:
      "After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed, becoming the Flash, fighting crime in Central City.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 1 Primetime Emmy. 29 wins & 90 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/akuD37ySZGUkXR7LNb1oOHCboy8.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "7.6/10" }],
    Metascore: "N/A",
    imdbRating: "7.6",
    imdbVotes: "331,912",
    imdbID: "tt3107288",
    Type: "series",
    totalSeasons: "8",
    Response: "True",
  },
  {
    Title: "House",
    Year: "2004–2012",
    Rated: "TV-14",
    Released: "16 Nov 2004",
    Runtime: "44 min",
    genre: "Drama, Mystery",
    Director: "N/A",
    Writer: "David Shore",
    Actors: "Hugh Laurie, Omar Epps, Robert Sean Leonard",
    Plot:
      "An antisocial maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases that come his way using his crack team of doctors and his wits.",
    Language: "English",
    Country: "United States",
    Awards: "Won 5 Primetime Emmys. 57 wins & 140 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/hiK4qc0tZijQ9KNUnBIS1k4tdMJ.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.7/10" }],
    Metascore: "N/A",
    imdbRating: "8.7",
    imdbVotes: "439,759",
    imdbID: "tt0412142",
    Type: "series",
    totalSeasons: "8",
    Response: "True",
  },
  {
    Title: "The Silent Sea",
    Year: "2021–",
    Rated: "TV-MA",
    Released: "24 Dec 2021",
    Runtime: "N/A",
    genre: "Adventure, Drama, Mystery",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Bae Doona, Gong Yoo, Joon Lee",
    Plot:
      "During a perilous 24-hour mission on the moon, space explorers try to retrieve samples from an abandoned research facility steeped in classified secrets.",
    Language: "Korean",
    Country: "South Korea",
    Awards: "N/A",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/9hNJ3fvIVd4WE3rU1Us2awoTpgM.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "6.9/10" }],
    Metascore: "N/A",
    imdbRating: "6.9",
    imdbVotes: "13,008",
    imdbID: "tt11570202",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "And Just Like That...",
    Year: "2021–",
    Rated: "TV-MA",
    Released: "09 Dec 2021",
    Runtime: "N/A",
    genre: "Comedy, Drama, Romance",
    Director: "N/A",
    Writer: "Michael Patrick King, Darren Star",
    Actors: "Sarah Jessica Parker, Cynthia Nixon, Kristin Davis",
    Plot:
      "The series will follow Carrie, Miranda and Charlotte as they navigate the journey from the complicated reality of life and friendship in their 30s to the even more complicated reality of life and friendship in their 50s.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/1CqkiWeuwlaMswG02q3mBmraiDM.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "5.4/10" }],
    Metascore: "N/A",
    imdbRating: "5.4",
    imdbVotes: "18,366",
    imdbID: "tt13819960",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "The Simpsons",
    Year: "1989–",
    Rated: "TV-PG",
    Released: "17 Dec 1989",
    Runtime: "22 min",
    genre: "Animation, Short, Comedy",
    Director: "N/A",
    Writer: "James L. Brooks, Matt Groening, Sam Simon",
    Actors: "Dan Castellaneta, Nancy Cartwright, Harry Shearer",
    Plot:
      "The satiric adventures of a working-class family in the misfit city of Springfield.",
    Language:
      "English, Spanish, Albanian, French, Japanese, German, Russian, Hindi, Swahili, Italian, Swedish, Turkish, Cantonese, Mandarin, Hebrew, Arabic, Klingon, Bengali, Czech, Chinese",
    Country: "United States",
    Awards: "Won 35 Primetime Emmys. 178 wins & 338 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/hpU2cHC9tk90hswCFEpf5AtbqoL.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.6/10" },
      { Source: "Rotten Tomatoes", Value: "89%" },
    ],
    Metascore: "N/A",
    imdbRating: "8.6",
    imdbVotes: "387,851",
    imdbID: "tt0096697",
    Type: "series",
    totalSeasons: "34",
    Response: "True",
  },
  {
    Title: "The Simpsons",
    Year: "1989–",
    Rated: "TV-PG",
    Released: "17 Dec 1989",
    Runtime: "22 min",
    genre: "Animation, Short, Comedy",
    Director: "N/A",
    Writer: "James L. Brooks, Matt Groening, Sam Simon",
    Actors: "Dan Castellaneta, Nancy Cartwright, Harry Shearer",
    Plot:
      "The satiric adventures of a working-class family in the misfit city of Springfield.",
    Language:
      "English, Spanish, Albanian, French, Japanese, German, Russian, Hindi, Swahili, Italian, Swedish, Turkish, Cantonese, Mandarin, Hebrew, Arabic, Klingon, Bengali, Czech, Chinese",
    Country: "United States",
    Awards: "Won 35 Primetime Emmys. 178 wins & 338 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/6Ys6koNajP5ld9EIMfOSQrRquki.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.6/10" },
      { Source: "Rotten Tomatoes", Value: "89%" },
    ],
    Metascore: "N/A",
    imdbRating: "8.6",
    imdbVotes: "387,851",
    imdbID: "tt0096697",
    Type: "series",
    totalSeasons: "34",
    Response: "True",
  },
  {
    Title: "Late Night with Jimmy Fallon",
    Year: "2009–2014",
    Rated: "TV-14",
    Released: "02 Mar 2009",
    Runtime: "60 min",
    genre: "Comedy, Music, Talk-Show",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Jimmy Fallon, The Roots, Steve Higgins",
    Plot: "Comedian Jimmy Fallon hosts a late-night talk show.",
    Language: "English",
    Country: "United States",
    Awards: "Won 2 Primetime Emmys. 5 wins & 17 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/uu5FuSKleCLh0Kq2pmGzlPH3aeS.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "6.8/10" }],
    Metascore: "N/A",
    imdbRating: "6.8",
    imdbVotes: "13,098",
    imdbID: "tt1231460",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
  },
  {
    Title: "Late Night with Conan O'Brien",
    Year: "1993–2009",
    Rated: "TV-14",
    Released: "13 Sep 1993",
    Runtime: "60 min",
    genre: "Comedy, Music, Talk-Show",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Conan O'Brien, The Max Weinberg 7, Andy Richter",
    Plot:
      "Conan O'Brien, a Harvard Lampoon alumnus, hosts this late-night comedy/talk-show, which is often silly and whimsical.",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Primetime Emmy. 8 wins & 55 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/q9unI9oHyLUNK97RQPYAGjFs4Xu.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.1/10" }],
    Metascore: "N/A",
    imdbRating: "8.1",
    imdbVotes: "17,900",
    imdbID: "tt0106052",
    Type: "series",
    totalSeasons: "17",
    Response: "True",
  },
  {
    Title: "The Daily Show with Trevor Noah: Ears Edition",
    Year: "2018–",
    Rated: "N/A",
    Released: "20 Feb 2018",
    Runtime: "N/A",
    genre: "Comedy",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Trevor Noah, Ronny Chieng, Michael Kosta",
    Plot:
      'Listen to highlights and extended interviews in the "Ears Edition" of The Daily Show with Trevor Noah. From Comedy Central\'s Podcast Network.',
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/uyilhJ7MBLjiaQXboaEwe44Z0jA.jpg",
    Ratings: [],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "tt13916212",
    Type: "series",
    totalSeasons: "N/A",
    Response: "True",
  },
  {
    Title: "Two and a Half Men",
    Year: "2003–2015",
    Rated: "TV-14",
    Released: "22 Sep 2003",
    Runtime: "22 min",
    genre: "Comedy, Romance",
    Director: "N/A",
    Writer: "Lee Aronsohn, Chuck Lorre",
    Actors: "Jon Cryer, Ashton Kutcher, Angus T. Jones",
    Plot:
      "A hedonistic jingle writer's free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.",
    Language: "English",
    Country: "United States",
    Awards: "Won 9 Primetime Emmys. 30 wins & 72 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/lW3r6Fb7dwZ0bpGwjYHMVkgSVRt.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "7.0/10" }],
    Metascore: "N/A",
    imdbRating: "7.0",
    imdbVotes: "253,658",
    imdbID: "tt0369179",
    Type: "series",
    totalSeasons: "12",
    Response: "True",
  },
  {
    Title: "Friends",
    Year: "1994–2004",
    Rated: "TV-PG",
    Released: "22 Sep 1994",
    Runtime: "22 min",
    genre: "Comedy, Romance",
    Director: "N/A",
    Writer: "David Crane, Marta Kauffman",
    Actors: "Jennifer Aniston, Courteney Cox, Lisa Kudrow",
    Plot:
      "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
    Language: "English, Spanish, Italian, French, Dutch, Hebrew",
    Country: "United States",
    Awards: "Won 6 Primetime Emmys. 77 wins & 220 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/ngoiHQul4QetfA62SdmZZOdDFAP.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.8/10" }],
    Metascore: "N/A",
    imdbRating: "8.8",
    imdbVotes: "928,567",
    imdbID: "tt0108778",
    Type: "series",
    totalSeasons: "10",
    Response: "True",
  },
  {
    Title: "That '70s Show",
    Year: "1998–2006",
    Rated: "TV-14",
    Released: "23 Aug 1998",
    Runtime: "22 min",
    genre: "Comedy, Drama, Romance",
    Director: "N/A",
    Writer: "Mark Brazill, Bonnie Turner, Terry Turner",
    Actors: "Topher Grace, Laura Prepon, Mila Kunis",
    Plot:
      "A comedy revolving around a group of teenage friends, their mishaps, and their coming of age, set in 1970s Wisconsin.",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Primetime Emmy. 15 wins & 77 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/3zRUiH8erHIgNUBTj05JT00HwsS.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.0/10" }],
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "163,020",
    imdbID: "tt0165598",
    Type: "series",
    totalSeasons: "8",
    Response: "True",
  },
  {
    Title: "The Fairly OddParents",
    Year: "2022–",
    Rated: "TV-Y7",
    Released: "N/A",
    Runtime: "N/A",
    genre: "Adventure, Comedy, Family",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Audrey Grace Marshall, Ryan-James Hatanaka, Daran Norris",
    Plot:
      'Follow Timmy Turner\'s cousin, Vivian "Viv" Turner, and her new stepbrother, Roy Ragland, as they navigate life in Dimmsdale with the help of their fairy godparents, Wanda and Cosmo.',
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/jlruzecsif3tkCSoHlUaPR01O7U.jpg",
    Ratings: [],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "tt15057532",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "Malcolm in the Middle",
    Year: "2000–2006",
    Rated: "TV-PG",
    Released: "09 Jan 2000",
    Runtime: "22 min",
    genre: "Comedy, Family",
    Director: "N/A",
    Writer: "Linwood Boomer, Michael Glouberman, Gary Murphy",
    Actors: "Frankie Muniz, Bryan Cranston, Justin Berfield",
    Plot:
      "A gifted young teen tries to survive life with his dimwitted, dysfunctional family.",
    Language: "English, Latin, Spanish, Italian, French, Chinese",
    Country: "United States",
    Awards: "Won 7 Primetime Emmys. 46 wins & 118 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/ysaA0BInz4071p3LKqAQnWKZCsK.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.1/10" }],
    Metascore: "N/A",
    imdbRating: "8.1",
    imdbVotes: "125,408",
    imdbID: "tt0212671",
    Type: "series",
    totalSeasons: "7",
    Response: "True",
  },
  {
    Title: "The X-Files",
    Year: "1993–2018",
    Rated: "TV-14",
    Released: "10 Sep 1993",
    Runtime: "45 min",
    genre: "Crime, Drama, Mystery",
    Director: "N/A",
    Writer: "Chris Carter",
    Actors: "David Duchovny, Gillian Anderson, Mitch Pileggi",
    Plot:
      "Two F.B.I. Agents, Fox Mulder the believer and Dana Scully the skeptic, investigate the strange and unexplained, while hidden forces work to impede their efforts.",
    Language: "English",
    Country: "United States",
    Awards: "Won 16 Primetime Emmys. 100 wins & 217 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/bti49Yh5yXrRvsionBGwbh4UKlP.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.6/10" }],
    Metascore: "N/A",
    imdbRating: "8.6",
    imdbVotes: "213,819",
    imdbID: "tt0106179",
    Type: "series",
    totalSeasons: "11",
    Response: "True",
  },
  {
    Title: "SpongeBob SquarePants",
    Year: "1999–",
    Rated: "TV-Y",
    Released: "01 May 1999",
    Runtime: "23 min",
    genre: "Animation, Comedy, Family",
    Director: "N/A",
    Writer: "Stephen Hillenburg, Tim Hill, Nick Jennings",
    Actors: "Tom Kenny, Bill Fagerbakke, Rodger Bumpass",
    Plot:
      "The misadventures of a talking sea sponge who works at a fast food restaurant, attends a boating school, and lives in an underwater pineapple.",
    Language: "English, Irish Gaelic, Korean",
    Country: "United States",
    Awards: "Nominated for 10 Primetime Emmys. 55 wins & 63 nominations total",
    Poster:
      "https://www.themoviedb.org/t/p/w1066_and_h600_bestv2/maFEWU41jdUOzDfRVkojq7fluIm.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "8.2/10" }],
    Metascore: "N/A",
    imdbRating: "8.2",
    imdbVotes: "91,921",
    imdbID: "tt0206512",
    Type: "series",
    totalSeasons: "13",
    Response: "True",
  },
];
